In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
%matplotlib inline

from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from pandas import get_dummies

from sklearn import datasets

In [4]:
data = pd.read_csv('Iris_dataset.csv')
data.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [6]:
X_input = data.drop(labels = 'Species', axis = 1)
# Y_label = data[['species']]

Y_label = data.iloc[:,4]
#Y_label = data.iloc[:,60]

In [8]:
X_input.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [9]:
Y_label.head()

0    setosa
1    setosa
2    setosa
3    setosa
4    setosa
Name: Species, dtype: object

In [34]:
from sklearn.preprocessing import LabelEncoder

In [46]:
LE= LabelEncoder()
y_encode = LE.fit_transform(data['Species'])
y_encode

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [40]:
y_hot = pd.get_dummies(y_encode)
y_hot.head()

0  1  2
0  1  0  0
1  1  0  0
2  1  0  0
3  1  0  0
4  1  0  0

In [42]:
y_hot = y_hot.values

In [44]:
#y_hot

In [14]:
# definining the perceptron

# define place holder for features and labels
x = tf.placeholder(tf.float32,[None,4]) # None becacuse we dont know the rows in dataset, and 4 is number of features or columns

y = tf.placeholder(tf.float32,[None,3]) # 3 is number of labels i.e in target variable(y)

In [15]:
# weights and bias

weight = tf.Variable(tf.truncated_normal([4,3], stddev = 0.1)) # initially taking weights as 'zeros', can be given random numbers,
                                                               #  4 is number of features, 3 is number of neurons
                                                               # stddev = 0.1 takes random values at 0.1 instead of infinity values
                                    

bias = tf.Variable(tf.truncated_normal([3],stddev = 0.1)) # here 3 neurans in this case

# input function

I = tf.add(tf.matmul(x,weight),bias)  # matmul = w1.x1 + w2.x2 + wn.xn....
                                      # bias = 1.w0

# activation function
output = tf.nn.softmax(I)

In [22]:
# this session is for creating the perception

In [16]:
# define the cost/loss functions and the optimizer

individual_loss = tf.nn.softmax_cross_entropy_with_logits_v2(labels = y, logits = output)
loss = tf.reduce_mean(individual_loss)

gdo = tf.train.GradientDescentOptimizer(learning_rate = 0.01)
train = gdo.minimize(loss)

In [17]:
# individualize the variables

init = tf.global_variables_initializer()

In [18]:
sess = tf.Session()
sess.run(init)
# sess.run(train) # once we feed the data we can 

In [19]:
for i in range(500000): # initially start with 100 check the accuracy and increase the value later to 500 you will get good accuracy
    final_train = sess.run(train,feed_dict={x:X_input,y:y_hot})

In [20]:
sess.run(weight)

array([[ 2.4831932,  1.6339262, -4.06859  ],
       [ 4.949261 ,  0.5031688, -5.3454742],
       [-6.6689143, -1.2850801,  7.933834 ],
       [-3.4213362, -3.5841587,  6.88394  ]], dtype=float32)

In [21]:
sess.run(bias)

array([ 1.0761995,  4.4568934, -5.6383743], dtype=float32)

In [22]:
predict = sess.run(output,feed_dict = {x:X_input})

In [23]:
predict

array([[9.99877453e-01, 1.22523066e-04, 4.98571886e-24],
       [9.98660564e-01, 1.33940286e-03, 3.17507119e-21],
       [9.99618769e-01, 3.81149788e-04, 3.49037099e-22],
       [9.98103023e-01, 1.89690548e-03, 3.48520176e-20],
       [9.99914527e-01, 8.55119579e-05, 3.42917717e-24],
       [9.99921918e-01, 7.80784903e-05, 7.13546698e-24],
       [9.99712527e-01, 2.87462957e-04, 1.03515282e-21],
       [9.99643564e-01, 3.56375560e-04, 1.15731360e-22],
       [9.96811330e-01, 3.18870856e-03, 2.34825590e-19],
       [9.98504996e-01, 1.49500242e-03, 1.74271930e-21],
       [9.99933124e-01, 6.68691937e-05, 3.83822246e-25],
       [9.99276698e-01, 7.23321515e-04, 1.84739986e-21],
       [9.98518169e-01, 1.48184947e-03, 2.18111553e-21],
       [9.99548972e-01, 4.51043335e-04, 7.23204959e-22],
       [9.99997497e-01, 2.49457889e-06, 1.59274030e-29],
       [9.99997735e-01, 2.23265738e-06, 3.13313846e-28],
       [9.99990940e-01, 9.06343121e-06, 2.07345079e-26],
       [9.99879479e-01, 1.20544

In [24]:
result = sess.run(tf.argmax(predict,1))

In [25]:
result

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [47]:
accuracy_score(result,y_encode)

0.98

In [48]:
confusion_matrix(result,y_encode)

array([[50,  0,  0],
       [ 0, 47,  0],
       [ 0,  3, 50]], dtype=int64)